### ISSUE TITLE
Error that breaks Quick Races

### ISSUE THREAD

**Issue by JustBru00** [Makkuusen/TimingSystem#277]
Error in console:
```[08:50:48 ERROR]: Thread TaskChainAsyncQueue Thread 1 failed main thread check: Cannot remove entity off-main
java.lang.Throwable: null
        at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:72) ~[paper-1.20.1.jar:git-Paper-174]
        at net.minecraft.world.entity.Entity.setRemoved(Entity.java:4655) ~[paper-1.20.1.jar:git-Paper-174]
        at net.minecraft.world.entity.Entity.remove(Entity.java:699) ~[paper-1.20.1.jar:git-Paper-174]
        at net.minecraft.world.entity.LivingEntity.remove(LivingEntity.java:759) ~[?:?]
        at net.minecraft.world.entity.Entity.discard(Entity.java:681) ~[paper-1.20.1.jar:git-Paper-174]
        at org.bukkit.craftbukkit.v1_20_R1.entity.CraftEntity.remove(CraftEntity.java:715) ~[paper-1.20.1.jar:git-Paper-174]
        at me.makkuusen.timing.system.track.GridManager.lambda$clearArmorstands$1(GridManager.java:56) ~[TimingSystem-1.8.1.jar:?]
        at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1779) ~[?:?]
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
        at me.makkuusen.timing.system.track.GridManager.clearArmorstands(GridManager.java:56) ~[TimingSystem-1.8.1.jar:?]
        at me.makkuusen.timing.system.heat.Heat.resetHeat(Heat.java:275) ~[TimingSystem-1.8.1.jar:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
        at java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
        at me.makkuusen.timing.system.event.EventDatabase.lambda$initDatabaseSynchronizeAsync$0(EventDatabase.java:50) ~[TimingSystem-1.8.1.jar:?]
        at me.makkuusen.timing.system.taskchain.TaskChain.done(TaskChain.java:1139) ~[TimingSystem-1.8.1.jar:?]
        at me.makkuusen.timing.system.taskchain.TaskChain.nextTask(TaskChain.java:1174) ~[TimingSystem-1.8.1.jar:?]
        at me.makkuusen.timing.system.taskchain.TaskChain.access$1000(TaskChain.java:57) ~[TimingSystem-1.8.1.jar:?]
        at me.makkuusen.timing.system.taskchain.TaskChain$TaskHolder.next(TaskChain.java:1357) ~[TimingSystem-1.8.1.jar:?]
        at me.makkuusen.timing.system.taskchain.TaskChain$TaskHolder.run(TaskChain.java:1312) ~[TimingSystem-1.8.1.jar:?]
        at me.makkuusen.timing.system.taskchain.TaskChain$TaskHolder.access$100(TaskChain.java:1266) ~[TimingSystem-1.8.1.jar:?]
        at me.makkuusen.timing.system.taskchain.TaskChain.lambda$nextTask$18(TaskChain.java:1187) ~[TimingSystem-1.8.1.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[08:50:48 ERROR]: [global] TaskChain Exception on Done Hander: Cannot remove entity off-main
[08:50:48 ERROR]: [global] Current Action Index was: 0
[08:50:48 WARN]: java.lang.IllegalStateException: Cannot remove entity off-main
[08:50:48 WARN]:        at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:73)
[08:50:48 WARN]:        at net.minecraft.world.entity.Entity.b(Entity.java:4655)
[08:50:48 WARN]:        at net.minecraft.world.entity.Entity.a(Entity.java:699)
[08:50:48 WARN]:        at net.minecraft.world.entity.EntityLiving.a(EntityLiving.java:759)
[08:50:48 WARN]:        at net.minecraft.world.entity.Entity.ai(Entity.java:681)
[08:50:48 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.entity.CraftEntity.remove(CraftEntity.java:715)
[08:50:48 WARN]:        at TimingSystem-1.8.1.jar//me.makkuusen.timing.system.track.GridManager.lambda$clearArmorstands$1(GridManager.java:56)
[08:50:48 WARN]:        at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1779)
[08:50:48 WARN]:        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
[08:50:48 WARN]:        at TimingSystem-1.8.1.jar//me.makkuusen.timing.system.track.GridManager.clearArmorstands(GridManager.java:56)
[08:50:48 WARN]:        at TimingSystem-1.8.1.jar//me.makkuusen.timing.system.heat.Heat.resetHeat(Heat.java:275)
[08:50:48 WARN]:        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
[08:50:48 WARN]:        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
[08:50:48 WARN]:        at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
[08:50:48 WARN]:        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[08:50:48 WARN]:        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[08:50:48 WARN]:        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[08:50:48 WARN]:        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
[08:50:48 WARN]:        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[08:50:48 WARN]:        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
[08:50:48 WARN]:        at TimingSystem-1.8.1.jar//me.makkuusen.timing.system.event.EventDatabase.lambda$initDatabaseSynchronizeAsync$0(EventDatabase.java:50)
[08:50:48 WARN]:        at TimingSystem-1.8.1.jar//me.makkuusen.timing.system.taskchain.TaskChain.done(TaskChain.java:1139)
[08:50:48 WARN]:        at TimingSystem-1.8.1.jar//me.makkuusen.timing.system.taskchain.TaskChain.nextTask(TaskChain.java:1174)
[08:50:48 WARN]:        at TimingSystem-1.8.1.jar//me.makkuusen.timing.system.taskchain.TaskChain.access$1000(TaskChain.java:57)
[08:50:48 WARN]:        at TimingSystem-1.8.1.jar//me.makkuusen.timing.system.taskchain.TaskChain$TaskHolder.next(TaskChain.java:1357)
[08:50:48 WARN]:        at TimingSystem-1.8.1.jar//me.makkuusen.timing.system.taskchain.TaskChain$TaskHolder.run(TaskChain.java:1312)
[08:50:48 WARN]:        at TimingSystem-1.8.1.jar//me.makkuusen.timing.system.taskchain.TaskChain$TaskHolder.access$100(TaskChain.java:1266)
[08:50:48 WARN]:        at TimingSystem-1.8.1.jar//me.makkuusen.timing.system.taskchain.TaskChain.lambda$nextTask$18(TaskChain.java:1187)
[08:50:48 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[08:50:48 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[08:50:48 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[08:50:48 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[08:50:48 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

Steps to reproduce:
Start server.
Create quick race
wait 60 seconds
start quick race
error will appear during race - All scoreboards and checkpoints in the race stop working. Race cannot be ended with /race end

Server setup information:
![image](https://github.com/Makkuusen/TimingSystem/assets/11063799/76909640-532e-4432-aca9-ff6cca10a354)
![image](https://github.com/Makkuusen/TimingSystem/assets/11063799/3ffc4869-0083-4c55-a4ad-f404205ed61c)
TimingSystem 1.8.1

**Comment by JustBru00** [comment]
I wonder if this is caused by creating an event before finished loading events is complete
