### ISSUE TITLE
Database error upgrading from 1.9 to 2.0.1

### ISSUE THREAD

**Issue by JustBru00** [Makkuusen/TimingSystem#359]
```
[19:22:33 WARN]: java.sql.SQLSyntaxErrorException: BLOB, TEXT, GEOMETRY or JSON column 'item' can't have a default value
[19:22:33 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
[19:22:33 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
[19:22:33 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:916)
[19:22:33 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1061)
[19:22:33 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1009)
[19:22:33 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1320)
[19:22:33 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:994)
[19:22:33 WARN]:        at TimingSystem-2.0.1.jar//com.zaxxer.hikari.proxy.PreparedStatementProxy.executeUpdate(PreparedStatementProxy.java:61)
[19:22:33 WARN]:        at TimingSystem-2.0.1.jar//com.zaxxer.hikari.proxy.HikariPreparedStatementProxy.executeUpdate(HikariPreparedStatementProxy.java)
[19:22:33 WARN]:        at TimingSystem-2.0.1.jar//me.makkuusen.timing.system.idb.DbStatement.executeUpdate(DbStatement.java:252)
[19:22:33 WARN]:        at TimingSystem-2.0.1.jar//me.makkuusen.timing.system.idb.Database.executeUpdate(Database.java:230)
[19:22:33 WARN]:        at TimingSystem-2.0.1.jar//me.makkuusen.timing.system.idb.DB.executeUpdate(DB.java:172)
[19:22:33 WARN]:        at TimingSystem-2.0.1.jar//me.makkuusen.timing.system.database.MySQLDatabase.createTables(MySQLDatabase.java:316)
[19:22:33 WARN]:        at TimingSystem-2.0.1.jar//me.makkuusen.timing.system.database.MySQLDatabase.initialize(MySQLDatabase.java:51)
[19:22:33 WARN]:        at TimingSystem-2.0.1.jar//me.makkuusen.timing.system.TimingSystem.onEnable(TimingSystem.java:124)
[19:22:33 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
[19:22:33 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
[19:22:33 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[19:22:33 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[19:22:33 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:640)
[19:22:33 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:551)
[19:22:33 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635)
[19:22:33 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434)
[19:22:33 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
[19:22:33 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1100)
[19:22:33 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[19:22:33 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by Pigalala** [comment]
yeah @Makkuusen this is the issue i brought up with you before where giving a longtext a default value destroys it (?), looks like we may actually need to fix it now :(

**Comment by Makkuusen** [comment]
@JustBru00 Can you see if this fixes the issue? https://github.com/Makkuusen/TimingSystem/releases/tag/2.0.2

**Comment by Makkuusen** [comment]
> yeah @Makkuusen this is the issue i brought up with you before where giving a longtext a default value destroys it (?), looks like we may actually need to fix it now :(

Weird issue indeed. So the default value is not needed, but it has worked with all mysql servers I've tried.

**Comment by JustBru00** [comment]
Upgrades properly when using 2.0.2.

```
[16:37:20 INFO]: [WorldGuard] Loading region data...
[16:37:20 INFO]: [TimingSystem] Enabling TimingSystem v2.0.2
[16:37:20 INFO]: [TimingSystem] [ACF] Enabled Asynchronous Tab Completion Support!
[16:37:20 INFO]: [TimingSystem] [ACF] Enabled Brigadier Support!
[16:37:21 INFO]: [TimingSystem] Connecting to Database: mysql://localhost:3307/frosthex_local_dev
[16:37:21 INFO]: [com.zaxxer.hikari.HikariDataSource] TimingSystem DB - is starting.
[16:37:21 WARN]: [TimingSystem] UPDATING DATABASE FROM 1.9 to 1
[16:37:21 WARN]: [TimingSystem] UPDATING DATABASE FROM 1 to 3
[16:37:23 INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[16:37:23 INFO]: [TimingSystem] LOADING IN Bahrain
```
