### ISSUE TITLE
Make sure stuff doesn't lock up when server is restarted while a heat is in loaded or running mode.

### ISSUE THREAD

**Issue by Makkuusen** [Makkuusen/TimingSystem#52]

**Comment by Makkuusen** [comment]
When a heat is stuck in LOADED it can't be reset cause scoreboards throw null exception.

[09:07:08 ERROR]: [TimingSystem] [ACF] Exception in command: heat load F2
[09:07:08 ERROR]: [TimingSystem] [ACF] java.lang.NullPointerException: Cannot invoke "me.makkuusen.timing.system.heat.DriverScoreboard.removeScoreboard()" because "this.scoreboard" is null
[09:07:08 ERROR]: [TimingSystem] [ACF]  at TimingSystem-1.0-rc.1.jar//me.makkuusen.timing.system.participant.Driver.updateScoreboard(Driver.java:50)
[09:07:08 ERROR]: [TimingSystem] [ACF]  at TimingSystem-1.0-rc.1.jar//me.makkuusen.timing.system.heat.Heat.lambda$updateScoreboard$4(Heat.java:242)

**Comment by Makkuusen** [comment]
Fixed in commit https://github.com/Makkuusen/TimingSystem/commit/559844e9ced4246b504ff0cc296b2d5a26a14383
